const FamilyGroupRequiredFields = {
  firstName: false,
  secondName: false,
  firstLastName: false,
  secondLastName: false,
  type: false,
  number: false,
  city: false,
  date: false,
  id: false,
  country: false,
  address: false,
  department: false,
  zipCode: false,
  landlinePhone: false,
  cellPhone: false,
  email: false,
  birthDate: false,
  gender: false,
  relationship: true,
  isDependent: true,
  educationLevel: false,
  businessActivity: false,
  profession: false,
};

export { FamilyGroupRequiredFields };
