const familyGroupRequiredFields = {
  firstName: true,
  secondName: false,
  firstLastName: true,
  secondLastName: true,
  type: true,
  identificationNumber: false,
  city: false,
  date: false,
  id: false,
  country: false,
  address: false,
  department: false,
  zipCode: false,
  landlinePhone: false,
  cellPhone: true,
  email: true,
  birthDate: false,
  gender: false,
  relationship: true,
  isDependent: true,
  educationLevel: false,
  businessActivity: false,
  profession: false,
};

export { familyGroupRequiredFields };
