const EconomicActivityRequiredFields = {
  economicActivity: false,
  profession: false,
  job: false,
  mainCiiuActivity: false,
  secondaryCiiuActivity: false,
  economicSector: false,
  company: false,
  contractType: false,
  admissionDate: false,
  contractExpiration: false,
  severanceRegime: false,
  workday: false,
  position: false,
  dependence: false,
  employeeCode: false,
  companyFormality: false,
  companyCountry: false,
  companyCity: false,
  companyPhone: false,
  companyAddress: false,
  companyEmail: false,
};

export { EconomicActivityRequiredFields };
