import { IProgrammedSavingProduct } from "../types";

const loadingProductsData: IProgrammedSavingProduct[] = [
  {
    id: "Cargando",
    title: "Cargando",
    maxRate: 0,
    maxDeadline: 0,
    maxQuota: 0,
    minQuota: 0,
    minDeadline: 0,
    deadlineType: "Discretional",
  },
  {
    id: "Cargando",
    title: "Cargando",
    maxRate: 0,
    maxDeadline: 0,
    maxQuota: 0,
    minQuota: 0,
    minDeadline: 0,
    deadlineType: "Discretional",
  },
  {
    id: "Cargando",
    title: "Cargando",
    maxRate: 0,
    maxDeadline: 0,
    maxQuota: 0,
    minQuota: 0,
    minDeadline: 0,
    deadlineType: "Discretional",
  },
  {
    id: "Cargando",
    title: "Cargando",
    maxRate: 0,
    maxDeadline: 0,
    maxQuota: 0,
    minQuota: 0,
    minDeadline: 0,
    deadlineType: "Discretional",
  },
  {
    id: "Cargando",
    title: "Cargando",
    maxRate: 0,
    maxDeadline: 0,
    maxQuota: 0,
    minQuota: 0,
    minDeadline: 0,
    deadlineType: "Discretional",
  },
  {
    id: "Cargando",
    title: "Cargando",
    maxRate: 0,
    maxDeadline: 0,
    maxQuota: 0,
    minQuota: 0,
    minDeadline: 0,
    deadlineType: "Discretional",
  },
];

export { loadingProductsData };
